name: housing
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pandas=2.1.1
- scikit-learn=1.3.1
- gunicorn=23.0.0
- uvicorn=0.35.0
- fastapi=0.116.1
- requests=2.32.4
- matplotlib=3.8.2